---
- name: Configuring AppArmor
  template:
    src: etc/apparmor.d/tunables/alias.j2
    dest: /etc/apparmor.d/tunables/alias
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Restart AppArmor
  service:
    name: apparmor
    state: restarted
  become: true