---
- name: Querying helm jetstack repo
  shell: helm repo list | grep -w jetstack
  failed_when: _repo.rc !=0 and _repo.rc != 1
  register: _repo

- name: Adding jetstack repo
  command: helm repo add jetstack https://charts.jetstack.io
  when: _repo.rc != 0

- name: Generating CA root
  shell: >
    [ -f ca.key ] || openssl req -x509 -sha256 -newkey rsa:2048
    -keyout ca.key -out ca.crt
    -days 356 -nodes -subj '/CN=mycluster'

- name: Querying cert-manager charts
  shell: helm list -n cert-manager -o json  | jq -r '.[].name' | grep -w cert-manager-1
  failed_when: _helm.rc !=0 and _helm.rc != 1
  register: _helm

- name: Adding cert-manager helm chart
  command: >
    helm upgrade --install --wait cert-manager-1 jetstack/cert-manager
    --namespace cert-manager --create-namespace
    --version v0.16.1
    --set installCRDs=true
  when: _helm.rc != 0

- name: Deleting secret
  command: kubectl delete secret ca-key-pair --namespace cert-manager
  failed_when: _helm.rc !=0 and _helm.rc != 1
  when: _helm.rc != 0

- name: Adding secret
  command: >
    kubectl create secret generic ca-key-pair
    -n cert-manager
    --from-file=tls.crt=ca.crt
    --from-file=tls.key=ca.key
  when: _helm.rc != 0

- name: Adding ingress
  shell: |
    cat << EOF | kubectl create -f -
    apiVersion: cert-manager.io/v1alpha2
    kind: ClusterIssuer
    metadata:
        name: ca-issuer
        namespace: cert-manager
    spec:
        ca:
            secretName: ca-key-pair
    EOF
  when: _helm.rc != 0
