# kubectl create secret docker-registry <name> \
# --docker-server=<your-registry-server> \
# --docker-username=<your-name> \
# --docker-password=<your-pword> \
# --docker-email=<your-email>
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg
    image: jlptf/privateapp   <=== 指定使用私有映像檔
    imagePullPolicy: Always
  imagePullSecrets:   <=== 下載映像檔時套用先前建立的 Secret 物件
  - name: regsecret
