---
- hosts: drbd1
  vars_files:
    - user_vars.yml
  tasks:
    - name: Copy kubeconfig to temporary file
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/kubeconfig-drbd
        remote_src: yes
      become: true

    - name: Replace server to {{ drbd_vip }}
      replace:
        path: /tmp/kubeconfig-drbd
        regexp: "127.0.0.1"
        replace: "{{ drbd_vip }}"
      become: true

    - name: Copy kubeconfig to local kubeconfig-drbd
      fetch:
        src: /tmp/kubeconfig-drbd
        dest: kubeconfig-drbd
        flat: yes
      become: true

    - name: Remove temporary file
      file:
        path: /tmp/kubeconfig-drbd
        state: absent   
      become: true   