all:
  hosts:
    manager1:
      ansible_host: 10.144.48.104
    manager2:
      ansible_host: 10.144.48.105
  children:
    drbd:
      hosts:
        manager1:
        manager2:
    managers:
      hosts:
        manager1:
        manager2:
    workers:
      hosts: {}

# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html