---
galaxy_info:
  author: Doro Wu
  description: packages
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - networking
    - system

dependencies: []
