---
galaxy_info:
  author: Doro Wu
  description: Do apt update
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy
  galaxy_tags:
    - networking
    - system

dependencies: []
