---
- name: Installing MySQL
  apt:
    name: mysql-server
  become: true
  register: result
  until: result is successful

- name: Stop heartbeat
  service:
    name: heartbeat
    state: stopped
  become: true

- name: Promote to primary
  command: drbdadm primary r0
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Mount DRBD
  command: mount -t ext4 /dev/drbd0 /opt/nfs
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Remove {{ mysql_datadir }}
  file:
    path: "{{ mysql_datadir }}"
    state: absent
  become: true
  when: >
    mysql_clean

- name: Querying mysqld changed
  command: grep -q {{ mysql_datadir }} /etc/mysql/mysql.conf.d/mysqld.cnf
  register: _mysql_mysqld_cnf_status
  ignore_errors: yes
  when: >
    inventory_hostname == groups[drbd_group][0]

- include_tasks: user.yml
  when: >
    inventory_hostname == groups[drbd_group][0] and _mysql_mysqld_cnf_status.rc != 0

- name: Querying {{ mysql_datadir }} stat
  stat:
    path: "{{ mysql_datadir }}"
  register: _mysql_datadir_stat
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Copying {{ mysql_datadir }}
  shell: |
    mkdir -p {{ mysql_datadir }}
    chown -R mysql:mysql {{ mysql_datadir }}
    chmod 700 {{ mysql_datadir }}
    cp -ar /var/lib/mysql/* {{ mysql_datadir }}/
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0] and not _mysql_datadir_stat['stat']['exists']

- include_tasks: apparmor.yml

- name: Configuring MySQL
  template:
    src: etc/mysql/mysql.conf.d/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Adding Heartbeat MySQL script
  template:
    src: etc/ha.d/resource.d/mysql
    dest: /etc/ha.d/resource.d/mysql
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Configuring Heartbeat MySQL resource
  shell: grep -q mysql /etc/ha.d/haresources || sed -i 's/drbddisk.*/& mysql/' /etc/ha.d/haresources
  become: true

- name: Tear down
  command: umount /opt/nfs
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Tear down
  command: drbdadm secondary r0
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Start heartbeat
  service:
    name: heartbeat
    state: started
  become: true

- name: Waiting primary node
  command: drbd-overview
  become: true
  register: _drbd_sync
  until: ('Primary' in _drbd_sync['stdout'])
  retries: 30
  delay: 5
  when: >
    inventory_hostname == groups[drbd_group][0]