---
- name: Installing MySQL
  apt:
    name: mysql-server
  become: true
  register: result
  until: result is successful

- name: Stop secondary heartbeat
  service:
    name: heartbeat
    state: stopped
  become: true
  when: >
        inventory_hostname != groups[drbd_group][0]

- name: Waiting primary node
  command: drbd-overview
  become: true
  register: _drbd_sync
  until: ('Primary/Secondary' in _drbd_sync['stdout'])
  retries: 20
  delay: 5
  when: >
        inventory_hostname == groups[drbd_group][0]        

# TODO restore default config
# TODO restore default heartbeat haresource
# TODO add mysql client cnf
- name: Start mysql
  service:
    name: mysql
    state: started
  become: true
  when: >
        inventory_hostname == groups[drbd_group][0]        

- name: Creating K3S user
  shell: |
    mysql -u root -f <<EOF
    DROP DATABASE IF EXISTS k3s;
    REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'k3s'@'%';
    DROP USER IF EXISTS 'k3s'@'%';
    CREATE DATABASE k3s;
    CREATE USER 'k3s'@'%' IDENTIFIED WITH mysql_native_password BY '{{ mysql_k3s_password }}';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON k3s.* TO 'k3s'@'%';
    EOF
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Stop and disable mysql
  service:
    name: mysql
    state: stopped
    enabled: no
  become: true

- name: Moving directory
  shell: |
    mkdir -p {{ mysql_datadir }}
    chown -R mysql:mysql {{ mysql_datadir }}
    chmod 700 {{ mysql_datadir }}
    cp -ar /var/lib/mysql/* {{ mysql_datadir }}/
  become: true
  when: >
    inventory_hostname == groups[drbd_group][0]

- name: Configuring AppArmor
  template:
    src: etc/apparmor.d/tunables/alias.j2
    dest: /etc/apparmor.d/tunables/alias
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Restart AppArmor
  service:
    name: apparmor
    state: restarted
  become: true  

- name: Configuring MySQL
  template:
    src: etc/mysql/mysql.conf.d/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Configuring Heartbeat script
  template:
    src: etc/ha.d/resource.d/mysql
    dest: /etc/ha.d/resource.d/mysql
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Configuring Heartbeat resource
  shell: grep -q mysql /etc/ha.d/haresources || sed -i 's/drbddisk.*/& mysql/' /etc/ha.d/haresources
  become: true

- name: Restart heartbeat
  service:
    name: heartbeat
    state: restarted
  become: true