apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /admin/grafana
        backend:
          serviceName: grafana
          servicePort: 80
