---
- name: Checking K3S exists
  stat:
    path: "/usr/local/bin/k3s"
  register: _k3s_master_binary_status

- name: Install K3S server
  shell: curl -sfL https://get.k3s.io | sh -s - --datastore-endpoint="mysql://k3s:{{ mysql_k3s_password }}@tcp({{ drbd_vip_ingress }}:3306)/k3s"
  become: true
  when: not _k3s_master_binary_status['stat']['exists']